[#####] - initramfs: Rework/Reorder/Cleanup the initramfs scripts.

diff --git a/recipes-core/initrdscripts/initramfs-netfield/device_data b/recipes-core/initrdscripts/initramfs-netfield/device_data
--- a/recipes-core/initrdscripts/initramfs-netfield/device_data
+++ b/recipes-core/initrdscripts/initramfs-netfield/device_data
@@ -4,129 +4,104 @@ device_data_enabled() {
 	return 0
 }
 
-FALLBACK_LABELS="backup rescue boot"
-
 device_data_run() {
-  echo "Running device_data ... "
+	# Create temporary module directory
+	moddir=/tmp/$module; mkdir -p $moddir
 
-  for fallback_label in ${FALLBACK_LABELS}; do
-    dev_list=$(blkid | grep "LABEL=\"$fallback_label\"" | cut -d ":" -f1)
-    for dev in $dev_list; do
-      if [ -n "${dev}" ]; then
-        mp="/mnt/$fallback_label-$(find /mnt/$fallback_label-* -type d -maxdepth 0 2>/dev/null | wc -l)"
-        mkdir -p ${mp}
-        mount ${dev} ${mp}
-      fi
-    done
-  done
+	dev=$(blkid -L backup)
+	mp=$(mktemp -d) && mkdir -p $mp && mount -o ro $dev $mp
 
-  mac=$(cat /sys/class/net/eth0/address | sed 's/://g' | tr "[:lower:]" "[:upper:]")
-  pub_key=/tmp/owner-public.key
-  openssl x509 -pubkey -in /proc/sys/srm/owner-cert -noout > ${pub_key}
+	# NOTE:
+	# As old INTEL devices/firmwares stored the device-label only in efivar,
+	# this migration step is carried out to copy this device-label to a common dedicated storage location.
+	[ ! -r $mp/nvd/device_data ] && {
+		load_kernel_module efivarfs && mount -t efivarfs none /sys/firmware/efi/efivars
+		[ -e /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9 ] && {
+			mount -o remount,rw $dev $mp && mkdir -p $mp/nvd
+			cat /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9 > $mp/nvd/device_data
+			mount -o remount,ro $dev $mp
+		}
+		[ -e /sys/firmware/efi/efivars ] && umount /sys/firmware/efi/efivars
+	}
 
-  load_kernel_module device-data
+	mac=$(cat /sys/class/net/eth0/address | tr -d ':' | tr "[:lower:]" "[:upper:]")
+	openssl x509 -pubkey -in /proc/sys/srm/owner-cert -noout > $moddir/owner-public.key
 
-  load_kernel_module efivarfs
-  [ -e /sys/firmware/efi/efivars ] && mount -t efivarfs none /sys/firmware/efi/efivars
+	dd=$mp/nvd/device_data
+	if [ -r $dd ]; then
+		# Split device data into signature and data
+		dd_sig=$(cut -d $'\n' -f1 < $dd)
+		dd_data=$(cut -d $'\n' -f2 < $dd)
 
-  # Verifying device data ...
-  for dd in /mnt/backup-*/nvd/device_data /mnt/rescue-*/nvd/device_data /mnt/boot-*/nvd/device_data /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9
-  do
-    if [ -r ${dd} ]; then
-      # Split device data into signature and data
-      tmp_sig=$(cat ${dd} | cut -d$'\n' -f1)
-      tmp_devdata=$(cat ${dd} | cut -d$'\n' -f2-)
+		base64 -i -d <<<$dd_sig > $moddir/dd.sig
 
-      # extract signature
-      dd_sig=/tmp/dd.sig
-      echo -n $tmp_sig | base64 -i -d - > ${dd_sig}
-      echo -n $tmp_devdata | openssl dgst -sha512 -verify "${pub_key}" -signature "${dd_sig}" && {
-        # Check against all found MAC's NOTE: Bluetooth and WIFI are not checked as this hacky split does not work for sub-objects
-        found_macs=`echo $tmp_devdata | tr -d "{}" | tr "," "\n" | grep "^\"mac" | cut -d ":" -f2 | tr -d "\"" | tr "\n" " "`
-        for dd_mac in $found_macs; do
-          if [ "$dd_mac" == "$mac" ]; then
-            # Export the device data
-            device_data=$tmp_devdata
-            signed_device_data=$(cat ${dd})
-            echo "Found device data on $dd"
-            break
-          fi
-        done
-        [ ! -z "$device_data" ] && break
-      }
+		__debug "Verifying $dd ..."
+		echo -n $dd_data | openssl dgst -sha512 -verify  $moddir/owner-public.key -signature $moddir/dd.sig && {
+			# Check against all found MAC's
+			grep -q mac\":\"$mac <<< $dd_data && {
+				device_data=$dd_data
+				__debug "... success => Using $dd as device_data file."
+			}
+		}
+		[ $device_data ] || __debug "... failed! => Using fake device data."
+	else
+		__debug "Invalid or missing device data! => Using fake device data."
+	fi
 
-      rm ${dd_sig}
-    fi
-  done
+	# Load kernel driver for securly providing device data in runtime environment.
+	load_kernel_module device-data
 
-  productname="unknown"
-  [ -e "/proc/device-tree/model" ] && productname=$(cat /proc/device-tree/model)
-  [ -e "/sys/class/dmi/id/product_name" ] && productname=$(cat /sys/class/dmi/id/product_name)
-  [ -e "/forced_productname" ] && productname=$(cat /forced_productname)
-  fallback_serial="MAC:$mac"
-  if [ -e "/sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574" ]; then
-    machine_id="$(cat /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574 | tail -c +5)"
-    modulus=$(openssl x509 -noout -modulus -in /proc/sys/srm/owner-cert | cut -d "=" -f2)
-    machine_id=$(echo $machine_id | openssl aes-256-cbc -nosalt -a -d -k "$modulus" -pbkdf2)
-    if [ $? -ne 0 ]; then
-        add_dl_data=',"product_number":"!!TAMPERED!!"'
-        fallback_serial="!!TAMPERED!!"
-        chattr -i /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574
-        rm -f /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574
-    else
-        add_dl_data=',"machine_id":"'"$machine_id"'"'
-        add_dl_data="${add_dl_data},"'"product_number":"'"$(echo $machine_id | head -c 12)"'"'
-        fallback_serial="$(echo $machine_id | tail -c 13)"
-    fi
-  fi
+	# Export device-/fake-data to runtime environment.
+	if [ $device_data ]; then
+		# Replace single backslash with double backslashes (some labels are non-standard JSON)
+		echo -n $device_data |  sed -e 's,\([^\\]\\\)\([^\\]\),\1\\\2,g' > /sys/device_data/export
+	else
+		# Define some defaults used to create fake device data.
+		productname="unknown"
+		[ -e "/proc/device-tree/model" ] && productname=$(cat /proc/device-tree/model)
+		[ -e "/sys/class/dmi/id/product_name" ] && productname=$(cat /sys/class/dmi/id/product_name)
+		[ -e "/forced_productname" ] && productname=$(cat /forced_productname)
 
-  if [ -z "$device_data" ]; then
-    # Insert fallback data to show error in edge gw manager
-    echo -n '{"product_name":"'"${productname}"'","serial_number":"'"${fallback_serial}"'"'"${add_dl_data}"'}' > /sys/device_data/export
-  else
-    # Replace single backslash with double backslashes (some labels are non-standard JSON)
-    echo -n $device_data |  sed -e 's,\([^\\]\\\)\([^\\]\),\1\\\2,g' > /sys/device_data/export
-    if [ $? -ne 0 ]; then
-      # Unable to inject device data (e.g. INVALID JSON),
-      # insert fallback data to show error in edge gw manager
-      echo -n '{"product_name":"'"${productname}"'","serial_number":"'"${fallback_serial}"'"'"${add_dl_data}"'}' > /sys/device_data/export
-    fi
+		fallback_serial="MAC:$mac"
 
-    # Restore efivars if not available
-    if [ -d /sys/firmware/efi/efivars ]; then
-      if [ ! -e /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9 ]; then
-        # create
-        printf "\x07\x00\x00\x00" > /tmp/efivars_temp
-        echo "$signed_device_data" >> /tmp/efivars_temp
-        cat /tmp/efivars_temp > /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9
-        rm /tmp/efivars_temp
-      fi
-    fi
-  fi
+		# NOTE:
+		# Since there are no device labels for virtual machines, the efivar hmi-* is used to provide
+		# additional unique informations about the machine.
+		# These are required for onboarding devices to the cloud.
+		# NOTE:
+		# Maybe this can be deleted in the future!
+		if [ -e "/sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574" ]; then
+			machine_id="$(cat /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574 | tail -c +5)"
+			modulus=$(openssl x509 -noout -modulus -in /proc/sys/srm/owner-cert | cut -d "=" -f2)
+			machine_id=$(echo $machine_id | openssl aes-256-cbc -nosalt -a -d -k "$modulus" -pbkdf2)
+			if [ $? -ne 0 ]; then
+				add_dl_data=',"product_number":"!!TAMPERED!!"'
+				fallback_serial="!!TAMPERED!!"
+				chattr -i /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574
+				rm -f /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574
+			else
+				add_dl_data=',"machine_id":"'"$machine_id"'"'
+				add_dl_data="${add_dl_data},"'"product_number":"'"$(echo $machine_id | head -c 12)"'"'
+				fallback_serial="$(echo $machine_id | tail -c 13)"
+			fi
+		fi
 
-  signature="${tmp_sig:-"na"}"
-  pubkey="$(cat $pub_key)"
-  echo -n '{"signature":"'"${signature}"'"}' > /sys/device_data/export
-  echo -n '{"publickey":"'"${pubkey}"'"}' | sed 's,\n,\\n,' > /sys/device_data/export
-  echo 1 > /sys/device_data/lock
+		echo -n '{"product_name":"'"${productname}"'","serial_number":"'"${fallback_serial}"'"'"${add_dl_data}"'}' > /sys/device_data/export
+	fi
 
-  ln -s /sys/device_data /var/platform/device_data
+	# Export the device-data signature as well as the public device key to runtime environment.
+	signature="${dd_sig:-"na"}"
+	pubkey="$(cat $moddir/owner-public.key)"
+	echo -n '{"signature":"'"${signature}"'"}' > /sys/device_data/export
+	echo -n '{"publickey":"'"${pubkey}"'"}' | sed 's,\n,\\n,' > /sys/device_data/export
 
-  for fallback_label in ${FALLBACK_LABELS}; do
-    mp_list="find /mnt/$fallback_label-* -type d -maxdepth 0 2>/dev/null"
-    for mp in $mp_list; do
-      if [ -d "${mp}" ]; then
-        # Restore on BACKUP if not available
-        if [ -n "$device_data" ]; then
-          if [ ! -e "${mp}/nvd/device_data" ]; then
-            mkdir -p ${mp}/nvd
-            echo -n "$signed_device_data" > ${mp}/nvd/device_data
-          fi
-        fi
-        umount ${mp}
-        rmdir ${mp}
-      fi
-    done
-  done
-  [ -e /sys/firmware/efi/efivars ] && umount /sys/firmware/efi/efivars
+	# Lock the kernel driver to prevent later tampering.
+	echo 1 > /sys/device_data/lock
+
+	# Provide a link in /var/platform
+	ln -s /sys/device_data /var/platform/device_data
+
+	# Cleanup
+	umount $mp  && rmdir $mp
+	rm -rf $moddir
 }
